services:
  qreceive:
    image: ghcr.io/driftwoodeval/questionnaires-qreceive:main
    container_name: qreceive
    environment:
      - HEADLESS=true
    volumes:
      - ./config:/app/config
      - ./put:/app/put
      - ./logs:/app/logs
    restart: unless-stopped

  config-server:
    image: ghcr.io/driftwoodeval/questionnaires-config-server:main
    container_name: config-server
    volumes:
      - ./config:/app/config
    ports:
      - "8000:8000"
    restart: unless-stopped
