name: Build and Push Docker Images

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for qreceive image
        id: meta-qreceive
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}-qreceive

      - name: Build and push qreceive image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: qreceive
          push: true
          tags: ${{ steps.meta-qreceive.outputs.tags }}
          labels: ${{ steps.meta-qreceive.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract metadata for config-server image
        id: meta-config-server
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}-config-server

      - name: Build and push config-server image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: config-server
          push: true
          tags: ${{ steps.meta-config-server.outputs.tags }}
          labels: ${{ steps.meta-config-server.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
